-- DROP DATABASE IF EXISTS jyk;
-- CREATE DATABASE jyk;
CREATE DATABASE IF NOT EXISTS jyk;
USE jyk;

CREATE TABLE `users` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(50) NOT NULL COMMENT '사용자 고유 아이디',
    `user_name` VARCHAR(50) NULL COMMENT '실명',
    `password` VARCHAR(50) NOT NULL COMMENT '비번',
    `email` VARCHAR(50) NULL COMMENT '사용자 이메일',
    `phone` VARCHAR(50) NULL COMMENT '사용자 전화번호',
    `users_created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `users_updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY user_uq (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '사용자 테이블';

CREATE TABLE `contracts` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `contract_id` VARCHAR(50) NOT NULL COMMENT '계약 고유 아이디',
    `user_id` VARCHAR(50) NOT NULL COMMENT '사용자 아이디',
    `contract_name` VARCHAR(50) NOT NULL COMMENT '계약명',
    `start_date` DATE NOT NULL COMMENT '시작일',
    `end_date` DATE NOT NULL COMMENT '종료일',
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '계약 테이블';

CREATE TABLE `products` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `product_name` VARCHAR(50) NOT NULL COMMENT '제품 이름',
    `price` DECIMAL(10,2) NOT NULL COMMENT '제품 가격',
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '제품 테이블';

CREATE TABLE `invoices` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(50) NOT NULL COMMENT '사용자 아이디',
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '송장 테이블';

CREATE TABLE `invoice_items` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `invoice_id` INT NOT NULL COMMENT '송장 아이디',
    `product_id` INT NOT NULL COMMENT '제품 아이디',
    `quantity` INT NOT NULL COMMENT '수량',
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '송장 품목 테이블';

CREATE TABLE `cars` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` VARCHAR(50) NOT NULL COMMENT '사용자 고유 아이디',
    `car_make` VARCHAR(50) NOT NULL COMMENT '자동차 제조사',
    `car_model` VARCHAR(50) NOT NULL COMMENT '자동차 모델명',
    `car_year` INT NOT NULL COMMENT '제조년도',
    `active` BOOLEAN NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci 
COMMENT '자동차 테이블';
