version: "3"
# tl(time-lens)
services:
  tl-db-local:
    container_name: tl-db-local
    image: mariadb:10.4
    restart: always
    ports: 
      - "51000:3306"
    volumes:
      - "../volumes/local/database/data:/var/lib/mysql"
      - "../volumes/local/database/sql:/docker-entrypoint-initdb.d"
      - "../volumes/local/database/conf.d:/etc/mysql/conf.d"
      - "../volumes/local/database/backup:/backup"
    env_file: .env
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - local
  tl-api-local:
    container_name: tl-api-local
    image: tl-api-local:0.0.1
    restart: always
    ports:
      - "51001:3000"
    volumes:
      - ../volumes/dev/api/logs:/app/logs
      - ../volumes/dev/api/public:/app/public
    build:
      context: ../code/back-end/api
      dockerfile: Dockerfile.local
    networks:
      - local
    env_file: .env.local
networks:
  local:
    driver: bridge
